### PR TITLE
fix: replace deprecated typing.ByteString with Union[bytes, bytearray, memoryview]

### LINKED ISSUE #549: Using of `typing.ByteString` which will be removed in Python 3.14
According to [document of typing.ByteString](https://docs.python.org/3.13/library/typing.html#typing.ByteString), it _deprecated since version 3.9, will be removed in version 3.14_.

```pycon
$ python
Python 3.14.0a6 (main, Mar 15 2025, 08:53:03) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.version
'3.14.0a6 (main, Mar 15 2025, 08:53:03) [GCC 11.4.0]'
>>> import aiosmtpd
>>> aiosmtpd.__version__
'1.4.6'
>>> from aiosmtpd import smtp
Traceback (most recent call last):
  File "<python-input-5>", line 1, in <module>
    from aiosmtpd import controller
  File "/venv/py314/lib/python3.14/site-packages/aiosmtpd/controller.py", line 26, in <module>
    from aiosmtpd.smtp import SMTP
  File "/venv/py314/lib/python3.14/site-packages/aiosmtpd/smtp.py", line 40, in <module>
    from aiosmtpd.proxy_protocol import ProxyData, get_proxy
  File "/venv/py314/lib/python3.14/site-packages/aiosmtpd/proxy_protocol.py", line 12, in <module>
    from typing import Any, ByteString, Dict, Optional, Protocol, Tuple, Union
ImportError: cannot import name 'ByteString' from 'typing' (/usr/lib/python3.14/typing.py)
>>>
```

### PR DESCRIPTION
**Pull request by lingxiu58**
Closes #549

## Problem

`typing.ByteString` is deprecated since Python 3.9 and will be removed in Python 3.14. Currently `proxy_protocol.py` uses it in 6 type annotations.

## Fix

Replace all `ByteString` annotations with `Union[bytes, bytearray, memoryview]`, which is the explicit equivalent and works on Python 3.9+. The `ByteString` import is also removed from the `typing` import line.

### CODE REVIEW

**Review by webknjaz — APPROVED** [review]

**Comment by webknjaz** [comment]
Could you also update the docs similar to #556?
