### PR TITLE
Replace ByteString with bytearray

### LINKED ISSUE #549: Using of `typing.ByteString` which will be removed in Python 3.14
According to [document of typing.ByteString](https://docs.python.org/3.13/library/typing.html#typing.ByteString), it _deprecated since version 3.9, will be removed in version 3.14_.

```pycon
$ python
Python 3.14.0a6 (main, Mar 15 2025, 08:53:03) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.version
'3.14.0a6 (main, Mar 15 2025, 08:53:03) [GCC 11.4.0]'
>>> import aiosmtpd
>>> aiosmtpd.__version__
'1.4.6'
>>> from aiosmtpd import smtp
Traceback (most recent call last):
  File "<python-input-5>", line 1, in <module>
    from aiosmtpd import controller
  File "/venv/py314/lib/python3.14/site-packages/aiosmtpd/controller.py", line 26, in <module>
    from aiosmtpd.smtp import SMTP
  File "/venv/py314/lib/python3.14/site-packages/aiosmtpd/smtp.py", line 40, in <module>
    from aiosmtpd.proxy_protocol import ProxyData, get_proxy
  File "/venv/py314/lib/python3.14/site-packages/aiosmtpd/proxy_protocol.py", line 12, in <module>
    from typing import Any, ByteString, Dict, Optional, Protocol, Tuple, Union
ImportError: cannot import name 'ByteString' from 'typing' (/usr/lib/python3.14/typing.py)
>>>
```

### PR DESCRIPTION
**Pull request by manisandro**
Fixes build with python 3.14

### CODE REVIEW

File: aiosmtpd/proxy_protocol.py
Comment (Dreamsorcerer) [inline aiosmtpd/proxy_protocol.py:1]: Why bytearray? There are defaults here which are clearly bytes, not bytearray, and the docs suggest replacing it with Buffer.

**Comment by waynew** [comment]
Closes https://github.com/aio-libs/aiosmtpd/issues/549

File: aiosmtpd/proxy_protocol.py
Comment (waynew) [reply aiosmtpd/proxy_protocol.py:1]: Agreed; I'll have to take a closer look, but Buffer is probably the more correct option

**Comment by msapiro** [comment]
Python 3.14 is released. We need an aiosmtpd release that supports Python 3.14.

**Comment by fumiyas** [comment]
Dear maintainers, could you please proceed with the merge?

**Review by webknjaz — APPROVED** [review]

**Comment by webknjaz** [comment]
#575 covers the runtime changes. Feel free to port the docs changes for that in a separate PR.
